"""
PgvectorAdapter — PostgreSQL pgvector + tsvector Storage and Hybrid RRF Search

Handles all PostgreSQL operations: pgvector extension check, upsert with
ON CONFLICT, hybrid RRF search query (BM25 + semantic via FULL OUTER JOIN),
delete by plan_id, and bulk upsert. Uses SharedDatabaseAdapter and
@with_db_error_handling from shared infrastructure.
"""

import logging

from sqlalchemy import text as sa_text

from shared.database.adapter import SharedDatabaseAdapter
from shared.database.error_handler import with_db_error_handling

logger = logging.getLogger("vectorindex")


class PgvectorAdapter:
    """PostgreSQL pgvector + tsvector storage and hybrid RRF search."""

    def __init__(self, db_adapter: SharedDatabaseAdapter) -> None:
        """Initialize with shared database adapter.

        Args:
            db_adapter: SharedDatabaseAdapter for PostgreSQL connections.
        """
        self._db = db_adapter

    @with_db_error_handling
    async def check_pgvector_extension(self) -> bool:
        """Check if pgvector extension is installed in PostgreSQL.

        Returns:
            True if pgvector extension is available.
        """
        async with self._db.get_session() as session:
            result = await session.execute(
                sa_text("SELECT 1 FROM pg_extension WHERE extname = 'vector'")
            )
            row = result.fetchone()
            return row is not None

    @with_db_error_handling
    async def upsert_embedding(
        self,
        plan_id: str,
        intent_type: str,
        embedding: list[float],
        search_text: str,
    ) -> None:
        """Insert or update a plan embedding row.

        Uses INSERT ... ON CONFLICT (plan_id) DO UPDATE for idempotent upserts.
        The tsvector column is auto-generated by the database trigger.

        Args:
            plan_id: ULID plan identifier.
            intent_type: Plan intent type.
            embedding: 384-dim float vector.
            search_text: Text used for embedding and tsvector.
        """
        sql = sa_text("""
            INSERT INTO plan_embeddings (
                plan_id, intent_type, embedding, search_text, model_version
            ) VALUES (
                :plan_id, :intent_type, :embedding, :search_text,
                'all-MiniLM-L6-v2'
            )
            ON CONFLICT (plan_id) DO UPDATE SET
                intent_type = EXCLUDED.intent_type,
                embedding = EXCLUDED.embedding,
                search_text = EXCLUDED.search_text,
                model_version = EXCLUDED.model_version
        """)
        async with self._db.get_session() as session:
            await session.execute(
                sql,
                {
                    "plan_id": plan_id,
                    "intent_type": intent_type,
                    "embedding": str(embedding),
                    "search_text": search_text,
                },
            )
            await session.commit()

    @with_db_error_handling
    async def hybrid_search(
        self,
        query_embedding: list[float],
        query_text: str,
        intent_type: str | None,
        top_k: int,
        rrf_k: int = 60,
    ) -> list[dict]:
        """Execute hybrid RRF query combining BM25 and cosine similarity.

        Uses two CTEs (keyword and semantic) joined via FULL OUTER JOIN,
        with RRF score fusion.

        Args:
            query_embedding: 384-dim query vector.
            query_text: Query text for BM25 matching.
            intent_type: Optional intent_type filter (exact match).
            top_k: Maximum number of results.
            rrf_k: RRF constant (default 60).

        Returns:
            List of result dicts with plan_id, intent_type, rrf_score,
            keyword_rank, semantic_rank.
        """
        sql = sa_text("""
            WITH keyword AS (
                SELECT plan_id, intent_type,
                       ROW_NUMBER() OVER (
                           ORDER BY ts_rank_cd(tsv, query) DESC
                       ) AS rank_kw
                FROM plan_embeddings,
                     plainto_tsquery('english', :query_text) AS query
                WHERE tsv @@ plainto_tsquery('english', :query_text)
                  AND (:intent_type IS NULL OR intent_type = :intent_type)
                LIMIT 20
            ),
            semantic AS (
                SELECT plan_id, intent_type,
                       ROW_NUMBER() OVER (
                           ORDER BY embedding <=> :query_embedding
                       ) AS rank_vec
                FROM plan_embeddings
                WHERE (:intent_type IS NULL OR intent_type = :intent_type)
                ORDER BY embedding <=> :query_embedding
                LIMIT 20
            )
            SELECT COALESCE(k.plan_id, s.plan_id) AS plan_id,
                   COALESCE(k.intent_type, s.intent_type) AS intent_type,
                   COALESCE(1.0 / (:rrf_k + k.rank_kw), 0.0)
                     + COALESCE(1.0 / (:rrf_k + s.rank_vec), 0.0)
                     AS rrf_score,
                   k.rank_kw AS keyword_rank,
                   s.rank_vec AS semantic_rank
            FROM keyword k
            FULL OUTER JOIN semantic s USING (plan_id)
            ORDER BY rrf_score DESC
            LIMIT :top_k
        """)

        async with self._db.get_session() as session:
            result = await session.execute(
                sql,
                {
                    "query_text": query_text,
                    "query_embedding": str(query_embedding),
                    "intent_type": intent_type,
                    "rrf_k": rrf_k,
                    "top_k": top_k,
                },
            )
            rows = result.fetchall()
            return [
                {
                    "plan_id": row.plan_id,
                    "intent_type": row.intent_type,
                    "rrf_score": float(row.rrf_score),
                    "keyword_rank": (
                        int(row.keyword_rank) if row.keyword_rank is not None else None
                    ),
                    "semantic_rank": (
                        int(row.semantic_rank) if row.semantic_rank is not None else None
                    ),
                }
                for row in rows
            ]

    @with_db_error_handling
    async def delete_by_plan_id(self, plan_id: str) -> None:
        """Delete embedding row by plan_id. Idempotent.

        Args:
            plan_id: ULID plan identifier.
        """
        sql = sa_text("DELETE FROM plan_embeddings WHERE plan_id = :plan_id")
        async with self._db.get_session() as session:
            await session.execute(sql, {"plan_id": plan_id})
            await session.commit()

    @with_db_error_handling
    async def bulk_upsert(self, rows: list[dict]) -> int:
        """Batch upsert embedding rows.

        Args:
            rows: List of dicts with plan_id, intent_type, embedding,
                search_text keys.

        Returns:
            Count of rows upserted.
        """
        if not rows:
            return 0

        sql = sa_text("""
            INSERT INTO plan_embeddings (
                plan_id, intent_type, embedding, search_text, model_version
            ) VALUES (
                :plan_id, :intent_type, :embedding, :search_text,
                'all-MiniLM-L6-v2'
            )
            ON CONFLICT (plan_id) DO UPDATE SET
                intent_type = EXCLUDED.intent_type,
                embedding = EXCLUDED.embedding,
                search_text = EXCLUDED.search_text,
                model_version = EXCLUDED.model_version
        """)

        async with self._db.get_session() as session:
            for row in rows:
                await session.execute(
                    sql,
                    {
                        "plan_id": row["plan_id"],
                        "intent_type": row["intent_type"],
                        "embedding": str(row["embedding"]),
                        "search_text": row["search_text"],
                    },
                )
            await session.commit()
        return len(rows)
